[package]
name = "bevy_entity_lookup_macros"
version = "0.1.0"
edition = "2024"
license = "MIT OR Apache-2.0"
repository = "https://github.com/Koettlitz/elf"
description = "Derive macros for bevy_entity_lookup"

[lib]
proc-macro = true

[dependencies]
syn = { workspace = true, features = [ "full", "extra-traits" ] }
quote = { workspace = true } 
proc-macro2 = { workspace = true } 
proc-macro-crate = "3"
elf-macro-utils = { path = "../elf_macro_utils" }
serde = { workspace = true, optional = true }

[dev-dependencies]
bevy_entity_lookup = { path = "../bevy_entity_lookup" }
