[package]
name = "bevy_elf"
version = "0.1.0"
edition = "2024"
repository = "https://github.com/Koettlitz/elf"
license = "MIT OR Apache-2.0"
readme = "README.md"
description = "Serializable Bevy asset definitions that resolve string references into Handles"
keywords = ["bevy", "asset", "handles"]
categories = ["game-development"]

[features]
default = ["macros", "math", "app"]
app = ["dep:bevy_app"]
macros = ["dep:bevy_elf_macros"]
math = ["dep:bevy_math"]
image = ["dep:bevy_image"]

[dependencies]
bevy_elf_macros = { optional = true, path = "../bevy_elf_macros"}
bevy_asset = { workspace = true } 
bevy_app = { workspace = true, optional = true }
bevy_reflect = { workspace = true }
bevy_math = { workspace = true, optional = true, features = ["serialize"] }
bevy_image = { workspace = true, optional = true, features = ["serialize"] }
serde = { workspace = true }
ron = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
bevy_app = { workspace = true } 
bevy_asset = { workspace = true }
bevy_image = { workspace = true }
